### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by bls1999**
- The images on the Jiber blog entry work again
 - I added a description for the Jiber blog entry that has a note about Jiber being renamed to HiDB + a last modified datetime for the post
 - Fixed a few links here and there
 - Added a note to the Jiber post that it's been renamed to HiDB and changed the Jiber link to the github repo for HiDB (since hidb.io is currently pretty half-baked)
 - Removed calls for cover photos from the old site
 - Changed +++ to --- in all the posts. This accomplishes the same thing but looks better when viewing on github 🙂
 - Added your name for in all the posts' metadata as "author"... just in case anyone missed that it's your blog 🤔

Also: it's worth noting that I haven't tested any of these changes. So please do check them before you merge to the live server.

### CODE REVIEW

**Comment by jacob-grahn** [comment]
Thanks, I copied in a couple of the changes you made here. Some of the changes like changing +++ to --- seemed to make Hugo pretty mad. (Hugo is the program this site is using to generate html from these markdown files.)

**Comment by bls1999** [comment]
> Thanks

Sure thing!

> I copied in a couple of the changes you made here. Some of the changes like changing +++ to --- seemed to make Hugo pretty mad. (Hugo is the program this site is using to generate html from these markdown files.)

Interesting, I wonder why that is. The Hugo documentation's [quick-start guide](https://gohugo.io/getting-started/quick-start/) has the ---s listed and not the +++s. According to [this guide](https://gohugo.io/content-management/front-matter/), the supported formats are yaml, toml, and json.

**Comment by bls1999** [comment]
In case you still want input from this pull, I resolved some merge conflicts that arose from your recent commits. If not, you can go ahead and close this.

Hoping all is well in your neck of the woods! 😃

**Comment by jacob-grahn** [comment]
It looks like +++ might use a different variable definition syntax than ---
```
---
title: "My First Post"
---
```
```
+++
title = "My First Post"
+++
```

 ":" vs "="

**Comment by bls1999** [comment]
> It looks like +++ might use a different variable definition syntax than ---
> 
> ```
> ---
> title: "My First Post"
> ---
> ```
> 
> ```
> +++
> title = "My First Post"
> +++
> ```
> 
> ":" vs "="

[A-ha](https://www.youtube.com/watch?v=djV11Xbc914)! Good catch. If you want it changed, I could save you some work and do it for you.

**Comment by jacob-grahn** [comment]
Yeah, go for it! Thanks. How's life?

**Comment by bls1999** [comment]
> Yeah, go for it! Thanks. How's life?

Pretty good! Still doing the college thing. I'm probably going to end up switching to computer science... who could've seen that coming?? lol.

How about you? Anything exciting happening?

**Comment by bls1999** [comment]
(The --- conversion is done)

**Comment by jacob-grahn** [comment]
Well, merging this pull request is pretty exciting

**Pull request merged**
